services:
  db:
    image: postgres:alpine
    container_name: projeto_express_db
    ports:
      - "${POSTGRES_PORT_OUT}:${POSTGRES_PORT_IN}"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      TZ: ${TZ}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - express-network

  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: projeto_express
    restart: always
    working_dir: /usr/src/app
    environment:
      TZ: ${TZ}
      NODE_ENV: ${NODE_ENV}
      PORT: ${APP_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT_IN}
    depends_on:
      - db
    ports:
      - "${APP_PORT}:${APP_PORT}"
    command: npm start
    networks:
      - express-network

networks:
  express-network:
    driver: bridge

volumes:
  postgres_data:
